immich:
  persistence:
    library:
      enabled: true
      # existingClaim: "immich-library"
      # storageClass: "" 
    config:
      enabled: true
      size: 1Gi

postgresql:
  enabled: true
  auth:
    username: fran
    existingSecret: immich-secrets
    secretKeys:
      password: postgres-password
    database: immich
  primary:
    persistence:
      size: 8Gi

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      enabled: true
      size: 2Gi

ingress:
  main:
    enabled: false